### ISSUE TITLE
[Bug] Missing license

### ISSUE THREAD

**Issue by remram44** [kubecost/disk-autoscaler#14]
### Kubernetes Version

-

### Description

Repository has no license information

### Steps to reproduce

-

### Expected behavior

-

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
@chipzoller @avrodrigues5 still good to add Apache 2.0 license?

**Comment by chipzoller** [comment]
Thanks for the catch. Yes, it's Apache 2.0.
