### ISSUE TITLE
[Feature] Audit mode

### ISSUE THREAD

**Issue by chipzoller** [kubecost/disk-autoscaler#4]
### Problem Statement

Users would like to see the action DAS will take to ensure it will work according to expectations and also to ensure the risks are known.

### Solution Description

Enable an audit mode in DAS so users can see, perhaps via log messages, the actions DAS would take without having it actually perform any changes.

### Troubleshooting

- [x] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
Would be really cool to see expected savings as part of this!
